[package]
name = "siteprobe"
version = "1.4.0"
license = "MIT"
edition = "2024"
rust-version = "1.86"
authors = ["Martin Mahner <martin@elephant.house>"]
description = "CLI tool to fetch URLs from sitemap.xml, check their existence, and generate performance reports"
repository = "https://github.com/bartTC/siteprobe"
homepage = "https://barttc.github.io/siteprobe/"
readme = "README.md"
categories = [
    "command-line-utilities",
    "web-programming",
    "network-programming",
    "parsing",
    "web-programming::http-client"
]
keywords = [
    "sitemap",
    "url-checker",
    "http-monitoring",
    "web-crawler",
    "performance",
]


[dependencies]
base64 = "0.23.1"
clap = { version = "4.6.6", features = ["derive", "wrap_help"] }
console = "0.16.4"
csv = "1.4.0"
flate2 = "1.1"
futures = "0.3.34"
indicatif = "0.18.6"
prettytable = "0.10.0"
quick-xml = "0.42"
rand = "0.10.2"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "rustls"] }
tokio = { version = "1.53.1", features = ["fs", "macros", "rt-multi-thread", "sync", "time"] }
unicode-segmentation = "1.13.3"
url = "2.5.8"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
governor = "0.10.4"
shellexpand = "3.1.2"
toml = "1.1"

[dev-dependencies]
tempfile = "3.27.0"
wiremock = "0.6.5"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
